---
title: "featureselection"
author: "sarwar"
date: "July 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description of the work
```{r}
#Given dataset is a size of I GB individual log in data with 21 individual parameters such as timestamp, epoch time, user ID, individual cloud, connection status, MSISDN login submission failure status, user activation submission status, user authorization status, email verification status, email verification failure status, MSISDN register page, MSISDN register page submission failure status, availability, user denied authorization status, user succeeded authentication, email login submission status,  MSISDN login submission status, new user creation status, and user activation submission status.
```
## Process of the work
```{r}
#To develop a prediction model, we need to do the following steps:

#1. What are the individual data mean in the given data set?
#2. Using Features selections find the correlation between the data in the data set
#3. What are the dependent and independent data in the data set?
#4. Create linear regression model
#5. Find the coefficients and residual
#6. Determine the residual is appropriate or not?
#7. Predict value using the regression modle
#8. Cross validate the prediction model

```


```{r packages}
 require(leaps)
```

```{r packages2}
 require(MASS)
```
```{r}
data1 <- read.csv(file.choose(), header=T)
#setwd("d:/desktop/currentwork/teldata.csv")
```
```{r}
shortlist <- data1[,c("timeStamp","UserID", "CONNECT", "epoch_time")]
summary(shortlist)
```
```{r transfer data to r object}
Timestamp <- data1[,c("timeStamp")]
UserID <- data1[,c("UserID")]
Connect <- data1[,c("CONNECT")]
fit <- lm(Connect ~ Timestamp + UserID)
summary(fit)

```
```{r}
# Add fit lines
library(car) 
scatterplot(Connect ~ UserID | UserID, data=mtcars, 
  	xlab="Weight of Car", ylab="Miles Per Gallon", 
   main="Enhanced Scatter Plot", 
   labels=row.names(shortlist))
```
```{r}
# Scatterplot Matrices from the glus Package 
library(car)
scatterplot.matrix(~timeStamp+UserID+epoch_time|CONNECT, data=shortlist,
  	main="User's Connection status")
```
```{r}
# Another Spinning 3d Scatterplot
library(rgl)
plot3d(Timestamp, UserID, Connect, col="red", size=3)
```


```{r}
library("lattice")
```
```{r}
tstamp <- data1[,c("epoch_time","UserID")]
tstamp1 <- data1[,c("UserID","timeStamp")]
#xyplot(epoch_time ~ UserID, tstamp)
library("hexbin")
hexbinplot(UserID ~ epoch_time, tstamp,
           scales = list(x = list(log = 10, equispaced.log = FALSE)),
           aspect = 1, bins=50)
```

```{r}
#tstamp <- data1[,c("timeStamp","UserID")]
xyplot(UserID ~ timeStamp, data = tstamp1,
  xlab = "Snout vent length (inches) on log scale",
  ylab = "Weight (pounds) on log scale",
  main = "Alligators in Central Florida"
)

```

```{r}
regsubsets(timeStamp ~ epoch_time +UserID + CONNECT ,  data=shortlist, nvmax = 4)
```

```{r}
reg1=regsubsets(timeStamp ~ epoch_time +UserID + CONNECT + user_allowed_authorization + user_succeeded_authentication
+ msisdn_login_submitted,  data=data1, method="backward")
```

```{r}
summary(reg1)
```
```{r}
reg2=regsubsets(timeStamp ~ epoch_time +UserID + CONNECT + user_allowed_authorization + user_succeeded_authentication
+ msisdn_login_submitted,  data=data1, method="backward")
```
#Explanation of the result of summary
#for the best subset of size 1, it puts 1 star next to the variable that's in the best subset of size 1.
#for the best subset of size 2, it puts 2 stars next to the variables that are in the best subset of size 2
```{r}
summary(reg2)
```

```{r}
reg3=regsubsets(timeStamp ~ UserID + CONNECT + user_allowed_authorization,  data=data1, method="backward")
```
```{r reg3}
summary(reg3)
```
# Other useful functions 
```{r}
#reg4=data.frame(y <-c(UserID),x1=c(timeStamp))
```



```{r}
# diagnostic plots 
layout(matrix(c(1,2,3,4),8,8)) # optional 4 graphs/page 
plot(reg2)
```


```{r}
plot(reg2,scale="adjr2")
```
```{r}
#summary(lm(timeStamp~userID))
```

